version: "3"

services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      DB_HOST: db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
